apiVersion: v1
kind: ConfigMap
metadata:
  name: be-user-config
data:
  application-stg.yml: |
    server:
      port: 8080

    spring:
      datasource:
        url: jdbc:postgresql://coubee-postgres.c5g4a4ekcfvb.ap-northeast-2.rds.amazonaws.com:5432/coubee_user
        driver-class-name: org.postgresql.Driver
        hikari:
          connection-test-query: SELECT 1
          validation-timeout: 5000
      data:
        redis:
          host: coubee-valkey-rg.kvqdpd.ng.0001.apn2.cache.amazonaws.com
          port: 6379
          timeout: 6000
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update # 개발 환경용
        generate-ddl: true
        show-sql: true
        open-in-view: false
        properties:
          hibernate.default_schema: coubee_user
      kafka:
        bootstrap-servers: coubee-external-kafka-service:9092
    file:
      upload:
        base-dir: ${user.home}/Desktop/coubee-img
        resource-url: /images/**
    cloud:
      aws:
        region:
          static: ap-northeast-2
        s3:
          bucket: coubee-s3
        cloudfront:
          domain: d1du1htkbm5yt2.cloudfront.net
    management:
      endpoints:
        web:
          exposure:
            include: prometheus, health, info
      metrics:
        distribution:
          percentiles-histogram:
            http.server.requests: true
            hikaricp.connections.acquire: true
            hikaricp.connections.usage: true
          percentiles:
            http.server.requests: 0.95
            hikaricp.connections.acquire: 0.95
            hikaricp.connections.usage: 0.95
      prometheus:
        metrics:
          export:
            enabled: true