apiVersion: v1
kind: Service
metadata:
  name: coubee-be-user-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: coubee-be-user