apiVersion: v1
kind: Service
metadata:
  name: es-external
spec:
  clusterIP: None
  ports:
    - port: 9200

---

apiVersion: v1
kind: Endpoints
metadata:
  name: es-external
subsets:
  - addresses:
      - ip: 10.0.4.113
    ports:
      - port: 9200