apiVersion: v1
kind: Service
metadata:
  name: coubee-external-kafka-service
  namespace: default
spec:
  type: ExternalName
  externalName: kafka-nlb-49b3f1d86c144793.elb.ap-northeast-2.amazonaws.com